name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    
    - name: Setup go
      uses: actions/setup-go@v2.1.5
      
    - name: Build application
      run: make
    

